mybatis:
  mapper-locations: com/ty/dao/*.xml
  type-aliases-package: com.ty.entity
  configuration:
    auto-mapping-behavior: full
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/atmosphere              # 数据库名称
    username: root
    password: 123
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/resources/

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql